import { Bell, CheckCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNotificationMutations, useNotifications } from "@/hooks/use-notifications";
import { useToast } from "@/hooks/use-toast";
import { ApiError } from "@/lib/api";

const messageFor = (type: string) => type === "CONNECTION_REQUEST" ? "sent you a connection request" : type === "CONNECTION_ACCEPTED" ? "accepted your connection request" : "endorsed one of your skills";
const relativeTime = (value: string) => { const seconds = Math.max(1, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return `${seconds}s`; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h`; return `${Math.floor(hours / 24)}d`; };

export function NotificationPanel() { const query = useNotifications(); const mutations = useNotificationMutations(); const { toast } = useToast(); const data = query.data; const run = async (action: () => Promise<unknown>) => { try { await action(); } catch (error) { toast({ title: error instanceof ApiError ? error.message : "Notification update failed", variant: "destructive" }); } }; return <div className="relative"><details className="group"><summary className="flex h-9 cursor-pointer list-none items-center gap-2 rounded-lg border border-border px-3 text-xs text-muted-foreground transition-colors hover:border-primary hover:text-primary"><Bell size={15} /><span className="hidden sm:inline">Notifications</span>{(data?.unreadCount ?? 0) > 0 && <span className="grid min-w-5 place-items-center rounded-full bg-primary px-1.5 py-0.5 text-[10px] font-semibold text-primary-foreground">{data?.unreadCount}</span>}</summary><div className="absolute right-0 top-12 z-50 w-[min(22rem,calc(100vw-2rem))] rounded-2xl border border-border bg-[#15151e] p-3 shadow-2xl"><div className="flex items-center justify-between border-b border-border px-2 pb-3"><span className="font-mono text-[10px] uppercase tracking-[.15em] text-primary">Signal inbox</span><Button variant="ghost" size="sm" disabled={!data?.unreadCount || mutations.markAllRead.isPending} onClick={() => void run(() => mutations.markAllRead.mutateAsync())} className="h-7 gap-1 text-[10px]"><CheckCheck size={13} /> Read all</Button></div>{query.isLoading && <p className="px-2 py-6 text-sm text-muted-foreground">Loading notifications...</p>}{query.isError && <p className="px-2 py-6 text-sm text-destructive">Notifications are unavailable.</p>}{!query.isLoading && !query.isError && !data?.items.length && <p className="px-2 py-6 text-sm text-muted-foreground">No notifications yet.</p>}{data?.items.map((item) => <button key={item.id} type="button" disabled={item.read || mutations.markRead.isPending} onClick={() => void run(() => mutations.markRead.mutateAsync(item.id))} className={`flex w-full items-start gap-3 rounded-xl px-2 py-3 text-left transition-colors hover:bg-secondary/60 ${item.read ? "opacity-60" : "bg-primary/5"}`}><div className="grid h-8 w-8 shrink-0 place-items-center overflow-hidden rounded-lg bg-primary/10 text-xs text-primary">{item.actor.avatarUrl ? <img src={item.actor.avatarUrl} alt="" className="h-full w-full object-cover" /> : item.actor.name.slice(0, 2).toUpperCase()}</div><span className="min-w-0 text-xs leading-relaxed text-muted-foreground"><strong className="text-foreground">{item.actor.name}</strong> {messageFor(item.type)}<span className="ml-2 font-mono text-[9px] text-muted-foreground/70">{relativeTime(item.createdAt)}</span></span></button>)}</div></details></div>; }