import { useState } from "react";
import { ArrowLeft, Calendar, Pencil, Trash2 } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useBlog, useBlogMutations } from "@/hooks/use-blogs";
import { useAuthStore } from "@/store/auth-store";

const inlineMarkdown = (text: string) => text.split(/(`[^`]+`|\*\*[^*]+\*\*|\*[^*]+\*|\[[^\]]+\]\([^\s)]+\))/g).map((part, index) => { if (part.startsWith("`") && part.endsWith("`")) return <code key={index} className="rounded bg-secondary px-1.5 py-0.5 font-mono text-sm text-cyan-200">{part.slice(1, -1)}</code>; if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>; if (part.startsWith("*") && part.endsWith("*")) return <em key={index}>{part.slice(1, -1)}</em>; const link = part.match(/^\[([^\]]+)\]\(([^\s)]+)\)$/); if (link && /^https?:\/\//.test(link[2])) return <a key={index} href={link[2]} target="_blank" rel="noreferrer" className="text-primary underline">{link[1]}</a>; return part; });
const renderMarkdown = (source: string) => source.split(/\n{2,}/).map((block, index) => { const line = block.trim(); if (line.startsWith("```")) return <pre key={index} className="overflow-x-auto rounded-xl border border-border bg-background/70 p-4 font-mono text-sm text-cyan-200"><code>{line.replace(/^```[a-zA-Z0-9+#-]*\n?/, "").replace(/```$/, "")}</code></pre>; if (/^#{1,3} /.test(line)) return <h2 key={index} className="mt-8 text-3xl font-semibold tracking-[-.04em]">{inlineMarkdown(line.replace(/^#{1,3} /, ""))}</h2>; if (line.startsWith("> ")) return <blockquote key={index} className="border-l-2 border-primary pl-4 italic text-muted-foreground">{inlineMarkdown(line.slice(2))}</blockquote>; const listItems = line.split("\n").filter((item) => /^[-*] /.test(item)); if (listItems.length === line.split("\n").length && listItems.length) return <ul key={index} className="list-disc space-y-2 pl-6">{listItems.map((item) => <li key={item}>{inlineMarkdown(item.slice(2))}</li>)}</ul>; return <p key={index} className="leading-8 text-foreground/90">{inlineMarkdown(line)}</p>; });

export default function BlogDetail() { const [, params] = useRoute("/blogs/:id"); const query = useBlog(params?.id ?? ""); const { user } = useAuthStore(); const [, setLocation] = useLocation(); const { deleteBlog } = useBlogMutations(); const [confirm, setConfirm] = useState(false); if (query.isLoading) return <AppShell><div className="mx-auto max-w-3xl p-8 text-muted-foreground">Loading field note...</div></AppShell>; if (query.isError || !query.data) return <AppShell><div className="mx-auto max-w-3xl p-8"><p className="text-destructive">This blog post is unavailable.</p><Link href="/blogs" className="mt-4 inline-flex items-center gap-2 text-primary"><ArrowLeft size={15} /> Back to blogs</Link></div></AppShell>; const blog = query.data; const owner = user?.id === blog.authorId; return <AppShell><article className="mx-auto max-w-3xl px-5 py-8 sm:px-8 lg:py-12"><Link href="/blogs" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft size={15} /> Back to blogs</Link><header className="my-10 border-b border-border pb-8"><div className="flex flex-wrap items-center gap-3 font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground"><span className={blog.published ? "text-primary" : "text-orange-300"}>{blog.published ? "Published" : "Draft"}</span><span className="flex items-center gap-2"><Calendar size={12} /> {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(blog.createdAt))}</span></div><h1 className="mt-5 text-4xl font-semibold tracking-[-.065em] sm:text-6xl">{blog.title}</h1><p className="mt-5 text-sm text-muted-foreground">By {blog.author.name} <span className="text-primary">@{blog.author.username}</span></p>{owner && <div className="mt-6 flex gap-2"><Link href={`/blogs/${blog.id}/edit`}><Button variant="outline" className="gap-2"><Pencil size={14} /> Edit</Button></Link><Button variant="outline" onClick={() => setConfirm(true)} className="gap-2 text-destructive"><Trash2 size={14} /> Delete</Button></div>}</header><div className="space-y-5 text-base">{renderMarkdown(blog.content)}</div><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this field note?</AlertDialogTitle><AlertDialogDescription>This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={async () => { await deleteBlog.mutateAsync(blog.id); setLocation("/blogs"); }}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></article></AppShell>; }