import { AlertCircle, PenLine, Plus, RefreshCw } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/app-shell";
import { BlogCard } from "@/components/blog-card";
import { Button } from "@/components/ui/button";
import { useBlogs } from "@/hooks/use-blogs";
import { ApiError } from "@/lib/api";
import { useAuthStore } from "@/store/auth-store";

export default function Blogs() { const query = useBlogs(); const { isAuthenticated } = useAuthStore(); const blogs = query.data ?? []; return <AppShell><div className="mx-auto max-w-[1320px] px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><header className="relative flex flex-col justify-between gap-6 border-b border-border pb-8 sm:flex-row sm:items-end"><div><div className="mb-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.2em] text-primary"><PenLine size={14} /> Blog index / field notes</div><h1 className="text-4xl font-semibold tracking-[-.065em] sm:text-6xl">Ideas worth <span className="text-primary">sharing.</span></h1><p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">Technical notes, useful rabbit holes, and the context behind the work.</p></div>{isAuthenticated && <Link href="/blogs/new"><Button className="w-fit gap-2 rounded-full"><Plus size={16} /> Write a blog</Button></Link>}</header>{query.isLoading && <div className="grid gap-4 py-8 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="soft-card h-72 animate-pulse rounded-2xl" />)}</div>}{query.isError && <div className="soft-card mt-8 rounded-2xl p-8" role="alert"><AlertCircle className="text-destructive" /><p className="mt-4 font-medium">The blog index is unavailable.</p><p className="mt-2 text-sm text-muted-foreground">{query.error instanceof ApiError ? query.error.message : "Try the index again."}</p><Button variant="outline" onClick={() => query.refetch()} className="mt-5 gap-2"><RefreshCw size={14} /> Try again</Button></div>}{!query.isLoading && !query.isError && !blogs.length && <div className="soft-card mt-8 rounded-2xl border-dashed p-12 text-center"><PenLine className="mx-auto text-primary" /><h2 className="mt-5 text-2xl font-medium">No field notes yet.</h2><p className="mt-2 text-sm text-muted-foreground">Be the first developer to put an idea into the index.</p></div>}{blogs.length > 0 && <div className="grid gap-4 py-8 md:grid-cols-2 xl:grid-cols-3">{blogs.map((blog) => <BlogCard key={blog.id} blog={blog} />)}</div>}</div></AppShell>; }